### ISSUE TITLE
Allow specify other original image name/tag than latest

### ISSUE THREAD

**Issue by brpaz** [eclass/semantic-release-docker#66]
Hello.
I generally have an image with name `my-base-image:<commit_hash>` in my CI pipelines and don't have a "latest" tag.

I found that your plugin is hardcoding the "latest" part in the original image when doing `docker tag`, resulting in an error because I dont have latest tag. 

It would be nice to be able to specify the full original name or a different original tag.

The plugin could then create two tags automatically: the latest and the semantic version one.

For now the workaround was to create a "latest" tag myself before calling semantic-release.

Thank you.

**Comment by Ringeltier** [comment]
Would be a nice feature
